apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  JWT_SECRET: ${JWT_SECRET}

---
apiVersion: v1
kind: Secret
metadata:
  name: firebase-secret
type: Opaque
data:
  FIREBASE_API_KEY: ${FIREBASE_API_KEY}
  FIREBASE_PASSWORD: ${FIREBASE_PASSWORD}