apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: pramithamj/pft-ci-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: MONGODB_URL
              value: mongodb://mongodb:27017/pft-mern
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: PORT
              value: "8000"
          volumeMounts:
            - mountPath: /app/logs
              name: backend-logs
            - mountPath: /app
              name: backend-code
      volumes:
        - name: backend-logs
          persistentVolumeClaim:
            claimName: backend-logs-pvc
        - name: backend-code
          persistentVolumeClaim:
            claimName: backend-code-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-code-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: backend